apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::215446237872:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-w6SHP9E4Bibj
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::215446237872:user/vicky
      username: vicky
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-18T12:12:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1238"
  uid: 901c4c78-297a-4ac5-b092-6f21677fd7df
